### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by chentsulin**
Hi @flosse 
We're using this library in [Bottender](https://github.com/Yoctol/bottender). We found some dependencies of this library are quite outdated.

Would you mind merging this PR and releasing a new version?
Thank you a lot.

### CODE REVIEW

**Review by flosse — CHANGES_REQUESTED** [review]
I've been away from the JS world for a while but it's common to track the `package-lock.json` within library repositories?

**Comment by chentsulin** [comment]
@flosse 
Yes, it is intended to be committed into the repo. This paragraph on npm docs explains it very well: https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json

> package-lock.json is automatically generated for any operations where npm modifies either the node_modules tree, or package.json. It describes the exact tree that was generated, such that subsequent installs are able to generate identical trees, regardless of intermediate dependency updates.
> 
> This file is intended to be committed into source repositories, and serves various purposes:
> 
> - Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
> - Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.
> - Facilitate greater visibility of tree changes through readable source control diffs.
> - Optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.
> - As of npm v7, lockfiles include enough information to gain a complete picture of the package tree, reducing the need to read package.json files, and allowing for significant performance improvements.

**Review by flosse — APPROVED** [review]

**Comment by flosse** [comment]
@chentsulin Thanks a lot!

**Comment by chentsulin** [comment]
Hi @flosse
Would you mind doing me a favor to release a new version?

This command may help:

```sh
git checkout master && git pull origin master && npm version minor && npm publish . && git push origin master --tags
```

**Comment by LeoChen1002** [comment]
Hi @flosse

Please help us to release new version.
Thanks for your great support.

Regards,
Leo

**Pull request merged**
